Junhyung getactivequarterlist component
ucsb-cs156-f24/proj-courses-f24-01 pull request #23
Opened 2024-11-23 01:30 UTC by Neamal

Closes #8 

Finished the getActiveQuarterList method in the UCSBApiQuarterService file and created an endpoint called activeQuarters in the controllers file. Also created tests for both the getActiveQuarterList method as well as the endpoint. Passed all of the tests including coverage and stryker. Below is a picture of the component in Swagger as it lists all of the dates until 20244 which was listed in my test file.

![image](https://github.com/user-attachments/assets/b0526f77-3ba6-4763-8547-20404b5dbcbf)

2024-11-24 01:34 UTC, vincentc0202 approved these changes, later dismissed
Good concise tests and good job adding the backend part

2024-11-25 06:32 UTC, pconrad requested changes
https://ucsb-cs156.github.io/topics/code_reviews/commented_out_code.html#why-should-commented-out-code-be-removed

2024-11-25 06:32 UTC, pconrad commented on src/test/java/edu/ucsb/cs156/courses/controllers/UCSBAPIQuarterControllerTests.java
> +  //   }
https://ucsb-cs156.github.io/topics/code_reviews/commented_out_code.html#why-should-commented-out-code-be-removed

2024-11-25 16:35 UTC, pconrad approved these changes
Code LGTM.. but need to test with the setting of END_QTR in the future.

2024-11-25 16:37 UTC, pconrad commented
@Neamal this looks good, and I think we can get it merged soon.  Just one thing: can you do this on your dokku instance?

```
dokku config:set courses-dev-neamal END_QTR=20251
```

It should restart your app after you do this.  This is needed because otherwise, the endpoint will "count backwards" from the current quarter to the END_QTR, which is not what we want.   We need to test the app with values that are realistic.

Then I think we can get this one merged.

2024-11-25 20:50 UTC, merged