Cameron add finals info service v2
ucsb-cs156-f24/proj-courses-f24-01 pull request #32
Opened 2024-11-26 20:47 UTC by cameronbyrne4

NOTE: this is an updated branch of my previous code that won't have heinous merge conflicts, and thus should work better.

Completes: https://github.com/ucsb-cs156-f24/proj-courses-f24-01/issues/30
Base reference: https://github.com/ucsb-cs156-f24/proj-courses-f24-01/issues/6
TODO: dokku deployment?

Added back end for finals information. Added a method that finals info from an endpoint in the UCSB API, with tests. Also added endpoint where a given quarter (YYYYQ) and enrollment code will get the finals info.

2024-11-27 00:12 UTC, pconrad requested changes
See code review

2024-11-27 00:12 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/courses/controllers/ApiController.java
> +// testing how creating a draft pull request works! cameron
Can we remove this from the PR?

2024-11-27 00:18 UTC, vincentc0202 reviewed
Delete the commented out test

2024-11-27 00:52 UTC, cameronbyrne4 commented
Now deployed. Please review and add admin review label!

2024-11-27 01:08 UTC, vincentc0202 submitted a review, later dismissed
Looks good, everything looks synchronous

2024-11-27 01:08 UTC, cameronbyrne4 reviewed
Pretty sure I deleted in a recent commit

2024-11-27 01:08 UTC, cameronbyrne4 commented on src/main/java/edu/ucsb/cs156/courses/controllers/ApiController.java
> +// testing how creating a draft pull request works! cameron
done

2024-11-27 01:24 UTC, raysujf reviewed
I got an error in testing the finalinfo api implementation.
![Screen Shot 2024-11-26 at 5 23 51 PM](https://github.com/user-attachments/assets/b7717155-6d8f-4815-b729-3005748f81ae)
![Screen Shot 2024-11-26 at 5 24 11 PM](https://github.com/user-attachments/assets/b559ace1-91fe-49d6-9b2a-45ec4bc1fb97)

2024-11-27 18:42 UTC, pconrad approved these changes, later dismissed
Code still looks good... will try again to test on dokku

2024-11-28 21:05 UTC, raychen179 commented
LGTM!

2024-11-29 17:42 UTC, pconrad approved these changes
LGTM

2024-11-29 17:42 UTC, merged